<a href="https://colab.research.google.com/github/AmlanSamanta/TensorFlowExercises/blob/main/TFQuickStartBeginner_mnistDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [2]:
mnist = tf.keras.datasets.mnist
(x_train,y_train), (x_test, y_test) = mnist.load_data()
x_train,x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [5]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [6]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2956 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1424 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1078 - accuracy: 0.9681
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0882 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0752 - accuracy: 0.9766


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-10.138228 ,  -4.1748657,  -4.5613647,   7.5495973, -24.278757 ,
         11.047575 , -11.547589 ,  -6.4285192,  -9.310298 ,  -5.103656 ]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[6.1119032e-10, 2.3770131e-07, 1.6150167e-07, 2.9369811e-02,
        4.4159329e-16, 9.7062969e-01, 1.4931313e-10, 2.4962191e-08,
        1.3987564e-09, 9.3899558e-08]], dtype=float32)

In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0752 - accuracy: 0.9765 - 584ms/epoch - 2ms/step


[0.07516369968652725, 0.9764999747276306]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.86168464e-09, 5.91190741e-09, 2.63671586e-06, 3.09545831e-05,
        2.81792090e-10, 1.88249860e-08, 1.87509391e-13, 9.99947906e-01,
        9.25072641e-08, 1.83487118e-05],
       [8.06668936e-07, 1.00364494e-04, 9.99849439e-01, 4.65793746e-05,
        1.03785660e-14, 2.26085581e-06, 3.98099829e-08, 7.51308792e-13,
        4.20203207e-07, 6.76149837e-13],
       [7.34433527e-08, 9.98738706e-01, 6.79806108e-05, 3.46248544e-06,
        3.38860045e-05, 1.73509807e-06, 2.08376650e-06, 1.10080594e-03,
        5.07775039e-05, 4.60666342e-07],
       [9.99174654e-01, 2.69482925e-08, 2.81661378e-05, 1.50416440e-06,
        1.71052022e-06, 1.84337114e-06, 6.47802954e-05, 7.26861239e-04,
        2.89039931e-10, 5.26554572e-07],
       [3.10118448e-05, 3.87745613e-09, 1.10710671e-05, 1.54761295e-07,
        9.96813357e-01, 3.62368624e-08, 2.31101549e-05, 4.75010456e-04,
        1.28016416e-06, 2.64487672e-03]], dtype=float32)>

In [12]:
probability_model(x_test[:10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[7.86168375e-09, 5.91190741e-09, 2.63671564e-06, 3.09545794e-05,
        2.81792062e-10, 1.88249842e-08, 1.87509378e-13, 9.99947846e-01,
        9.25072570e-08, 1.83487118e-05],
       [8.06669050e-07, 1.00364501e-04, 9.99849558e-01, 4.65793819e-05,
        1.03785668e-14, 2.26085604e-06, 3.98099864e-08, 7.51308900e-13,
        4.20203236e-07, 6.76149891e-13],
       [7.34433527e-08, 9.98738706e-01, 6.79806108e-05, 3.46248544e-06,
        3.38860045e-05, 1.73509807e-06, 2.08376650e-06, 1.10080594e-03,
        5.07775039e-05, 4.60666342e-07],
       [9.99174654e-01, 2.69482925e-08, 2.81661378e-05, 1.50416440e-06,
        1.71052022e-06, 1.84337114e-06, 6.47802954e-05, 7.26861239e-04,
        2.89039931e-10, 5.26554572e-07],
       [3.10118448e-05, 3.87745613e-09, 1.10710671e-05, 1.54761295e-07,
        9.96813357e-01, 3.62368624e-08, 2.31101549e-05, 4.75010456e-04,
        1.28016416e-06, 2.64487672e-03],
       [8.39977776e-09, 9